stages:
  - build
  - deploy

image: ubuntu:latest

image: php:8.1.0

variables:
  # Set environment variables if needed

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - ./setup.sh


deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y sshpass
  when: on_success   # Run the deploy stage only when the build stage succeeds
  needs:
    - job: build
      artifacts: true 
