FROM php:8.1-fpm

# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libpq-dev \
    libonig-dev \
    libzip-dev \
    libwebp-dev \
    librdkafka-dev \
    net-tools

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install redis && docker-php-ext-enable redis

# Install extensions
RUN docker-php-ext-install pdo_pgsql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp
RUN docker-php-ext-install gd opcache
RUN pecl install rdkafka && docker-php-ext-enable rdkafka

# Install Swoole extension
RUN pecl install swoole
RUN docker-php-ext-enable swoole

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www-gbn
RUN useradd -u 1000 -ms /bin/bash -g www-gbn www-gbn

# Copy existing application directory contents
COPY --chown=www-gbn:www-gbn . /var/www

# Set permissions for storage directory
RUN chown -R www-gbn:www-gbn /var/www/storage
RUN chmod -R 775 /var/www/storage

# Change current user to www
USER www-gbn

CMD ["php", "artisan", "octane:start", "--workers=8", "--task-workers=16", "--host=0.0.0.0", "--max-requests=500","--port=9000"]
